name: Test REPOS Proposal Publisher

on: [push]

permissions:            # Explicitly set secrets permissions
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run REPOS Proposal Publisher
        uses: openteamsinc/repos-proposal-publisher@fix-npm
        with:
          token: ${{ secrets.GH_TOKEN }}
